<?php

return [
  "cars" => [
    [
      "name" => "Car Model 1",
      "cover_image" => "1.jpg",
      "price" => 25000,
      "km" => 50000,
      "date_of_enrollment" => "2020-01-15",
      "brand" => "12",
      "model" => "Corolla",
      "fuel_type" => "Gasoline",
      "transmission" => "Automatic",
      "engine_displacement" => 1600,
      "car_doors_number" => 4,
      "color" => "Blue",
      "description" => "A reliable and fuel-efficient car.",
    ],
    [
      "name" => "Car Model 2",
      "cover_image" => "auto-usata.jpg",
      "price" => 18000,
      "km" => 80000,
      "date_of_enrollment" => "2018-06-20",
      "brand" => "22",
      "model" => "Civic",
      "fuel_type" => "Hybrid",
      "transmission" => "CVT",
      "engine_displacement" => 1800,
      "car_doors_number" => 4,
      "color" => "Silver",
      "description" => "A stylish and eco-friendly car.",
    ],
    [
      "name" => "Luxury Sedan",
      "cover_image" => "11153871_O_5c91121d6e49f-1.jpg",
      "price" => 55000,
      "km" => 20000,
      "date_of_enrollment" => "2022-03-10",
      "brand" => "6",
      "model" => "E-Class",
      "fuel_type" => "Diesel",
      "transmission" => "Automatic",
      "engine_displacement" => 2200,
      "car_doors_number" => 4,
      "color" => "Black",
      "description" => "Experience luxury and performance.",
    ],
    [
      "name" => "Compact Hatchback",
      "cover_image" => "auto3.jpg",
      "price" => 15000,
      "km" => 35000,
      "date_of_enrollment" => "2019-11-05",
      "brand" => "24",
      "model" => "Focus",
      "fuel_type" => "Petrol",
      "transmission" => "Manual",
      "engine_displacement" => 1200,
      "car_doors_number" => 5,
      "color" => "Red",
      "description" => "A compact and efficient city car.",
    ],
  ],
  "car_brands" => [
    "Audi",
    "BMW",
    "Mercedes-Benz",
    "Volkswagen",
    "Ford",
    "Chevrolet",
    "Toyota",
    "Honda",
    "Nissan",
    "Volvo",
    "Porsche",
    "Ferrari",
    "Lamborghini",
    "Maserati",
    "Jaguar",
    "Land Rover",
    "Jeep",
    "Subaru",
    "Mazda",
    "Lexus",
    "Hyundai",
    "Kia",
    "Tesla",
    "Acura",
    "Cadillac",
    "GMC",
    "Buick",
    "Chrysler",
    "Dodge",
    "Ram",
    "Mitsubishi",
    "Infiniti",
    "Mini",
    "Alfa Romeo",
    "Fiat",
    "Renault",
    "Peugeot",
    "Citroën",
    "Skoda",
    "Seat",
    "Opel",
    "Smart",
  ]
];
